apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-project
  ports:
    - protocol: TCP
      port: 8080   # External port
      targetPort: 80  # Container's port
  type: NodePort  # Change to LoadBalancer if using cloud Kubernetes
